[http]
host = "0.0.0.0"
port = 8080

[postgres]
host        = "postgres"
port        = 5432
user        = "postgres"
password    = "postgres"
database    = "pr-reviewer-service-postgres"
sslmode     = "disable"